name: flutter_blue_background
description: A Flutter plugin for scanning BLE devices in background.
version: 0.0.2

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: com.sparkleo.flutter_blue_background.flutter_blue_background
        pluginClass: FlutterBlueBackgroundPlugin
